name: kdf
description: A tool for managing KDF files.
homepage: https://kauri.seanbailey.io
version: 0.1.0
author: Sean Bailey <sean@seanbailey.io>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  archive: ^2.0.10
  args: ^1.5.2
  xml: ^3.5.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
