name: kdf
version: 0.1.0
description: >-
  Dart KDF is command line application and Dart library for parsing and
  converting KDF documents.
repository: https://github.com/sean0x42/dart_kdf
homepage: https://kdf.now.sh
executables:
  kdf2pdf:

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  archive: ^2.0.11
  args: ^1.5.2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
