[book]
authors = ["Sean Bailey"]
language = "en"
multilingual = false
src = "src"
title = "KDF"
description = "A specification for the KDF document format."

[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/sean0x42/kdf"

[output.html.fold]
enable = true
